#registration
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
           client-name : kakao
           client-id : 8565cbcd7901cbd81614d0dce6184240
           client-secret : KD5pMfCvNmRQiNnsD2oEyyW6hMyftVLD
           redirect-uri : http://localhost:8080/login/oauth2/code/kakao
           authorization-grant-type : authorization_code
           scope : profile_nickname
           client-authentication-method: client_secret_post
  
#provider
        provider:
          kakao:
           authorization-uri : https://kauth.kakao.com/oauth/authorize
           token-uri : https://kauth.kakao.com/oauth/token
           user-info-uri : https://kapi.kakao.com/v2/user/me
           user-name-attribute : id